-- Create the resources table
create table resources (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text, -- Stores the note text or the URL
  type text not null check (type in ('note', 'link', 'image')),
  category text default 'Misc',
  image_url text -- For image resources or link previews
);

-- Enable Row Level Security (RLS)
alter table resources enable row level security;

-- Create a policy that allows anyone to read/write (for development)
-- You should change this to authenticated users only for production
create policy "Enable all access for all users" on resources
  for all using (true) with check (true);

-- Create a bucket for images if you want to support image uploads
insert into storage.buckets (id, name, public) values ('images', 'images', true);

-- Policy for storage (public access for dev)
create policy "Public Access" on storage.objects for all using ( bucket_id = 'images' );
